version: '3'
services:

  l2tp_vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: "l2tp_vpn"
    privileged: true
    restart: unless-stopped
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    environment:
      - VPN_IPSEC_PSK=${IPSEC_PRE_SHARED_KEY}
      - VPN_USER=${IPSEC_VPN_USERNAME}
      - VPN_PASSWORD=${IPSEC_VPN_PASSWORD}
    volumes:
      - /lib/modules:/lib/modules:ro

  sstp_vpn:
    image: fernandezcuesta/softethervpn
    container_name: "sstp_vpn"
    privileged: true
    restart: unless-stopped
    ports:
    - 443:443/tcp

    environment:
       - SSTP_ENABLED=true
       - USERNAME=${SSTP_VPN_USERNAME}
       - PASSWORD=${SSTP_VPN_PASSWORD}
       - CERT=${SSTP_VPN_CERT}
       - KEY=${SSTP_VPN_KEY}
    cap_add:
      - net_admin 
      - sys_module    