version: '3'
services:

  socks5:
    container_name: "socks5-proxy"
    build: 
      context: ./dante
      args:
        USER: hirkn
        PASS: SlavaKpss
    ports:
      - "8811:1080/tcp"
      - "8811:1080/udp"
    restart: always

  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    environment:
      - VPN_IPSEC_PSK=your_ipsec_pre_shared_key
      - VPN_USER=your_vpn_username
      - VPN_PASSWORD=your_vpn_password
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro

  telegram-proxy:
    image: telegrammessenger/proxy:latest
    container_name: "telegram-proxy"
    ports:
      - "444:443"
    environment:
       - WORKERS=4
    volumes:
       - "~/data:/data"
    restart: unless-stopped
    env_file:
       - ./config.env