version: '3'
services:

  socks5:
    container_name: "socks5-proxy"
    build: 
      context: ./dante
      args:
        USER: hirkn
        PASS: SlavaKpss
    ports:
      - "8811:1080/tcp"
      - "8811:1080/udp"
    restart: always

  openvpn:
    image: umputun/dockvpn
    container_name: "openvpn"
    ports:
      - "1194:1194/udp"
      - "443:443/tcp"
    restart: always    
    privileged: true
    volumes:
      - '~/.openvpn:/etc/openvpn'

  telegram-proxy:
    image: telegrammessenger/proxy:latest
    container_name: "telegram-proxy"
    ports:
      - "444:443"
    environment:
       - WORKERS=4
    volumes:
       - "~/data:/data"
    restart: unless-stopped
    env_file:
       - ./config.env